# Site settings
title: Nathan Builds Stuff
description: My journey learning and building things
baseurl: ""        # leave empty for root
url: "https://ngreen37.github.io"  

# Theme
theme: minima       

# Navigation
header_pages:
  - index.md
  - blog.md
